project_id = "elzqxtrncamxiymbjqio"

[functions.get-resources]
verify_jwt = true

[functions.get-calendar]
verify_jwt = true

[functions.mascot-message]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.sync-lesson-to-calendar]
verify_jwt = true
